// Package relay Code generated by swaggo/swag. DO NOT EDIT
package relay

import "github.com/swaggo/swag"

const docTemplaterelay = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Straw Proxy Support",
            "url": "https://github.com/kwilabs/straw-proxy-server"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api-keys": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns paginated list of all API keys (without raw key values)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "List API Keys",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of API keys",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ListApiKeysResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Creates a new API key. The raw key is returned only once in the response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Create API Key",
                "parameters": [
                    {
                        "description": "API key creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateApiKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created API key with raw key",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateApiKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api-keys/{id}": {
            "delete": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Revokes an API key by ID, preventing further use",
                "tags": [
                    "api-keys"
                ],
                "summary": "Revoke API Key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "API key revoked successfully"
                    },
                    "400": {
                        "description": "ID required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/billing/estimate": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns estimated billing cost for the specified time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usage"
                ],
                "summary": "Get Billing Estimate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, default: start of month)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, default: today)",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by API key ID",
                        "name": "api_key_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Billing estimate",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.BillingEstimateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid date format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cache/clear": {
            "post": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Clears Redis cache keys matching the specified pattern",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Clear Cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key pattern to match (default: *)",
                        "name": "pattern",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deletion result",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ClearCacheResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cache/stats": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns Redis server information and memory statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get Cache Stats",
                "responses": {
                    "200": {
                        "description": "Redis info",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.CacheStatsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/endpoints": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns all registered proxy endpoints with their health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "endpoints"
                ],
                "summary": "List Endpoints",
                "responses": {
                    "200": {
                        "description": "List of endpoints",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.EndpointHealthResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/endpoints/{id}/drain": {
            "post": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Marks an endpoint as draining, preventing new requests from being routed to it",
                "tags": [
                    "endpoints"
                ],
                "summary": "Drain Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Endpoint marked for draining"
                    },
                    "400": {
                        "description": "ID required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fingerprints": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns all available fingerprint presets for TLS fingerprinting",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fingerprints"
                ],
                "summary": "List Fingerprint Presets",
                "responses": {
                    "200": {
                        "description": "List of presets",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.FingerprintResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Creates a new fingerprint preset or updates an existing one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fingerprints"
                ],
                "summary": "Create or Update Fingerprint Preset",
                "parameters": [
                    {
                        "description": "Fingerprint preset",
                        "name": "preset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateFingerprintRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created or updated preset",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.FingerprintResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fingerprints/broadcast": {
            "post": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Sends all fingerprint presets to all connected endpoints via message broker",
                "tags": [
                    "fingerprints"
                ],
                "summary": "Broadcast Fingerprint Presets",
                "responses": {
                    "200": {
                        "description": "Presets broadcast successfully"
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns OK if the server is running",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Returns OK if the server is ready to accept traffic",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rules": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns paginated list of all routing rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routing-rules"
                ],
                "summary": "List Routing Rules",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of routing rules",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ListRoutingRulesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Creates a new routing rule for request matching",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routing-rules"
                ],
                "summary": "Create Routing Rule",
                "parameters": [
                    {
                        "description": "Routing rule to create",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateRoutingRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created routing rule",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RoutingRuleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/rules/{id}": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns a specific routing rule by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routing-rules"
                ],
                "summary": "Get Routing Rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Routing Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Routing rule",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RoutingRuleResponse"
                        }
                    },
                    "400": {
                        "description": "ID required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Rule not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Updates an existing routing rule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routing-rules"
                ],
                "summary": "Update Routing Rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Routing Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated routing rule",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.UpdateRoutingRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated routing rule",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RoutingRuleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or ID mismatch",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Deletes a routing rule by ID",
                "tags": [
                    "routing-rules"
                ],
                "summary": "Delete Routing Rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Routing Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Rule deleted successfully"
                    },
                    "400": {
                        "description": "ID required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usage/summary": {
            "get": {
                "security": [
                    {
                        "AdminKeyAuth": []
                    }
                ],
                "description": "Returns daily usage summaries for the specified time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usage"
                ],
                "summary": "Get Usage Summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, default: 30 days ago)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, default: today)",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by API key ID",
                        "name": "api_key_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usage summaries",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.UsageSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid date format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/request": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Proxies an HTTP request through a matched endpoint based on routing rules.\nThe request is validated, filtered, rate-limited, and executed through the endpoint pool.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "Relay HTTP Request",
                "parameters": [
                    {
                        "description": "HTTP request to proxy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful proxy response",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or URL",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Request blocked by filter or scope",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "No matching routing rule found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "502": {
                        "description": "Upstream execution failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/v2/request": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Proxies an HTTP request through a matched endpoint based on routing rules.\nThe request is validated, filtered, rate-limited, and executed through the endpoint pool.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relay"
                ],
                "summary": "Relay HTTP Request",
                "parameters": [
                    {
                        "description": "HTTP request to proxy",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful proxy response",
                        "schema": {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or URL",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Request blocked by filter or scope",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "404": {
                        "description": "No matching routing rule found",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "502": {
                        "description": "Upstream execution failed",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.ABConfigDTO": {
            "type": "object",
            "properties": {
                "strategy": {
                    "description": "Strategy determines how variants are selected (random, round_robin, weighted)",
                    "type": "string"
                },
                "variants": {
                    "description": "Variants are the different fingerprint options to test",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ABVariantDTO"
                    }
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.ABVariantDTO": {
            "type": "object",
            "properties": {
                "fingerprint": {
                    "description": "Fingerprint is the TLS fingerprint preset ID",
                    "type": "string"
                },
                "weight": {
                    "description": "Weight is the percentage weight for weighted selection (0-100)",
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.ApiKeyResponse": {
            "description": "API key data returned by the API (excludes token hash)",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is when the key was created",
                    "type": "string"
                },
                "expires_at": {
                    "description": "ExpiresAt is when the key expires (optional)",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for this API key",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive indicates whether this key is currently active",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is a human-readable name for the key",
                    "type": "string"
                },
                "rate_limit_override": {
                    "description": "RateLimitOverride allows per-key rate limit customization",
                    "type": "integer"
                },
                "scopes": {
                    "description": "Scopes define which tag patterns this key can access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.BillingEstimateResponse": {
            "description": "Response containing billing estimate for a date range",
            "type": "object",
            "properties": {
                "currency": {
                    "description": "Currency is the currency code (e.g., \"USD\")",
                    "type": "string"
                },
                "end": {
                    "description": "End date in YYYY-MM-DD format",
                    "type": "string"
                },
                "estimated_usd": {
                    "description": "EstimatedUSD is the estimated cost in USD",
                    "type": "number"
                },
                "start": {
                    "description": "Start date in YYYY-MM-DD format",
                    "type": "string"
                },
                "total_cost_units": {
                    "description": "TotalCostUnits is the sum of all cost units",
                    "type": "number"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.CacheStatsResponse": {
            "description": "Response containing Redis cache statistics",
            "type": "object",
            "properties": {
                "info": {
                    "description": "Info contains Redis server information",
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.ClearCacheResponse": {
            "description": "Response after clearing cache keys",
            "type": "object",
            "properties": {
                "deleted": {
                    "description": "Deleted is the number of keys removed",
                    "type": "integer"
                },
                "message": {
                    "description": "Message describes what was done",
                    "type": "string"
                },
                "pattern": {
                    "description": "Pattern is the key pattern that was matched",
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateApiKeyRequest": {
            "description": "Request body for creating a new API key",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name is a human-readable name for the key (required)",
                    "type": "string"
                },
                "rate_limit_override": {
                    "description": "RateLimitOverride allows per-key rate limit customization",
                    "type": "integer"
                },
                "scopes": {
                    "description": "Scopes define which tag patterns this key can access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateApiKeyResponse": {
            "description": "Response after creating an API key, includes raw key value",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is when the key was created",
                    "type": "string"
                },
                "expires_at": {
                    "description": "ExpiresAt is when the key expires (optional)",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for this API key",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive indicates whether this key is currently active",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is a human-readable name for the key",
                    "type": "string"
                },
                "rate_limit_override": {
                    "description": "RateLimitOverride allows per-key rate limit customization",
                    "type": "integer"
                },
                "raw_key": {
                    "description": "RawKey is the plain-text API key (only shown once during creation)",
                    "type": "string"
                },
                "scopes": {
                    "description": "Scopes define which tag patterns this key can access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateFingerprintRequest": {
            "description": "Request body for creating or updating a fingerprint preset",
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "config": {
                    "description": "Config is the detailed configuration of the fingerprint",
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "description": "ID is the unique identifier for this preset (required)",
                    "type": "string"
                },
                "name": {
                    "description": "Name is a human-readable name for the preset (required)",
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.CreateRoutingRuleRequest": {
            "description": "Request body for creating a new routing rule",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "allow_insecure_tls": {
                    "description": "AllowInsecureTLS allows skipping TLS certificate verification",
                    "type": "boolean"
                },
                "allowed_endpoint_types": {
                    "description": "AllowedEndpointTypes specifies which endpoint types can handle requests",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "endpoint_pools": {
                    "description": "EndpointPools defines tiered endpoint fallback pools",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.EndpointPoolDTO"
                    }
                },
                "excluded_tags": {
                    "description": "ExcludedTags are tags that a request must NOT have to match this rule",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fingerprint_ab_test": {
                    "description": "FingerprintABTest allows A/B testing different fingerprints",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ABConfigDTO"
                        }
                    ]
                },
                "fingerprint_preset": {
                    "description": "FingerprintPreset specifies the default browser TLS fingerprint",
                    "type": "string"
                },
                "hard_timeout": {
                    "description": "HardTimeout is the maximum time allowed for a request (e.g., \"30s\")",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive indicates whether this rule is currently active",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is a human-readable name for the rule (required)",
                    "type": "string"
                },
                "pinned_cert_hash": {
                    "description": "PinnedCertHash for certificate pinning",
                    "type": "string"
                },
                "priority": {
                    "description": "Priority determines rule precedence (higher = evaluated first)",
                    "type": "integer"
                },
                "quota_key": {
                    "description": "QuotaKey is the key used for rate limit bucketing",
                    "type": "string"
                },
                "rate_limit_per_minute": {
                    "description": "RateLimitPerMinute is the maximum requests per minute",
                    "type": "integer"
                },
                "rate_limit_per_second": {
                    "description": "RateLimitPerSecond is the maximum requests per second",
                    "type": "integer"
                },
                "request_filters": {
                    "description": "RequestFilters defines bandwidth optimization filters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RequestFilterDTO"
                        }
                    ]
                },
                "required_endpoint_caps": {
                    "description": "RequiredEndpointCaps are capability tags that endpoints must have",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "required_tags": {
                    "description": "RequiredTags are the tags that a request MUST have to match this rule",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.EndpointHealthResponse": {
            "description": "Health information for a registered endpoint",
            "type": "object",
            "properties": {
                "active_tasks": {
                    "description": "ActiveTasks is the number of in-flight requests",
                    "type": "integer"
                },
                "endpoint_id": {
                    "description": "EndpointID is the unique identifier",
                    "type": "string"
                },
                "last_seen": {
                    "description": "LastSeen is when the endpoint last reported in",
                    "type": "string"
                },
                "state": {
                    "description": "State is the current health state",
                    "type": "string"
                },
                "tags": {
                    "description": "Tags are the endpoint's capability tags",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "description": "Version is the endpoint software version",
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.EndpointPoolDTO": {
            "type": "object",
            "properties": {
                "endpoints": {
                    "description": "Endpoints are endpoint IDs or tag selectors for this pool",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_retries": {
                    "description": "MaxRetries is the maximum retry attempts within this pool",
                    "type": "integer"
                },
                "tier": {
                    "description": "Tier is the priority of this pool (1 = Primary, 2 = Secondary, etc.)",
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.FingerprintResponse": {
            "description": "Fingerprint preset data returned by the API",
            "type": "object",
            "properties": {
                "config": {
                    "description": "Config is the detailed configuration of the fingerprint",
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "description": "CreatedAt is when the preset was created",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for this preset",
                    "type": "string"
                },
                "name": {
                    "description": "Name is a human-readable name for the preset",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt is when the preset was last modified",
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.ListApiKeysResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ApiKeyResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.ListRoutingRulesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RoutingRuleResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayMetaDTO": {
            "type": "object",
            "properties": {
                "endpoint_id": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pool": {
                    "type": "string"
                },
                "retries": {
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayRequest": {
            "description": "HTTP request to be proxied through the relay",
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "body": {
                    "description": "Body is the request body",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "headers": {
                    "description": "Headers are the HTTP headers to send",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "ID is an optional client-provided request ID for correlation",
                    "type": "string"
                },
                "method": {
                    "description": "Method is the HTTP method (defaults to GET)",
                    "type": "string"
                },
                "session_id": {
                    "description": "SessionID for sticky session affinity",
                    "type": "string"
                },
                "timeout": {
                    "description": "Timeout is the request timeout (e.g., \"30s\")",
                    "type": "string"
                },
                "trace_id": {
                    "description": "TraceID for distributed tracing",
                    "type": "string"
                },
                "url": {
                    "description": "URL is the target URL to proxy (required)",
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayResponse": {
            "description": "Response from a proxied HTTP request",
            "type": "object",
            "properties": {
                "body": {
                    "description": "Body is the response body",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "headers": {
                    "description": "Headers from the target response",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "meta": {
                    "description": "Meta contains relay metadata",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RelayMetaDTO"
                        }
                    ]
                },
                "request_id": {
                    "description": "RequestID correlates to the original request",
                    "type": "string"
                },
                "session_id": {
                    "description": "SessionID if a session was created or used",
                    "type": "string"
                },
                "status_code": {
                    "description": "StatusCode is the HTTP status from the target",
                    "type": "integer"
                },
                "timing": {
                    "description": "Timing contains request timing breakdown",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.TimingDTO"
                        }
                    ]
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.RequestFilterDTO": {
            "type": "object",
            "properties": {
                "adblock_lists": {
                    "description": "AdblockLists specifies which blocklists to use",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "block_content_types": {
                    "description": "BlockContentTypes blocks responses by Content-Type",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "block_domains": {
                    "description": "BlockDomains blocks requests to specific domains",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "block_url_patterns": {
                    "description": "BlockURLPatterns blocks requests matching URL patterns",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "enable_adblock": {
                    "description": "EnableAdblock enables EasyList-style ad blocking",
                    "type": "boolean"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.RoutingRuleResponse": {
            "description": "Routing rule data returned by the API",
            "type": "object",
            "properties": {
                "allow_insecure_tls": {
                    "description": "AllowInsecureTLS allows skipping TLS certificate verification",
                    "type": "boolean"
                },
                "allowed_endpoint_types": {
                    "description": "AllowedEndpointTypes specifies which endpoint types can handle requests",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "description": "CreatedAt is when the rule was created",
                    "type": "string"
                },
                "endpoint_pools": {
                    "description": "EndpointPools defines tiered endpoint fallback pools",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.EndpointPoolDTO"
                    }
                },
                "excluded_tags": {
                    "description": "ExcludedTags are tags that a request must NOT have to match this rule",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fingerprint_ab_test": {
                    "description": "FingerprintABTest allows A/B testing different fingerprints",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ABConfigDTO"
                        }
                    ]
                },
                "fingerprint_preset": {
                    "description": "FingerprintPreset specifies the default browser TLS fingerprint",
                    "type": "string"
                },
                "hard_timeout": {
                    "description": "HardTimeout is the maximum time allowed for a request",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for this rule",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive indicates whether this rule is currently active",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is a human-readable name for the rule",
                    "type": "string"
                },
                "pinned_cert_hash": {
                    "description": "PinnedCertHash for certificate pinning",
                    "type": "string"
                },
                "priority": {
                    "description": "Priority determines rule precedence",
                    "type": "integer"
                },
                "quota_key": {
                    "description": "QuotaKey is the key used for rate limit bucketing",
                    "type": "string"
                },
                "rate_limit_per_minute": {
                    "description": "RateLimitPerMinute is the maximum requests per minute",
                    "type": "integer"
                },
                "rate_limit_per_second": {
                    "description": "RateLimitPerSecond is the maximum requests per second",
                    "type": "integer"
                },
                "request_filters": {
                    "description": "RequestFilters defines bandwidth optimization filters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RequestFilterDTO"
                        }
                    ]
                },
                "required_endpoint_caps": {
                    "description": "RequiredEndpointCaps are capability tags that endpoints must have",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "required_tags": {
                    "description": "RequiredTags are the tags that a request MUST have to match this rule",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "description": "UpdatedAt is when the rule was last modified",
                    "type": "string"
                },
                "version": {
                    "description": "Version for optimistic locking on updates",
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.TimingDTO": {
            "type": "object",
            "properties": {
                "dns_lookup": {
                    "type": "string"
                },
                "first_byte": {
                    "type": "string"
                },
                "tcp_connect": {
                    "type": "string"
                },
                "tls_handshake": {
                    "type": "string"
                },
                "total": {
                    "type": "string"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.UpdateRoutingRuleRequest": {
            "description": "Request body for updating an existing routing rule",
            "type": "object",
            "required": [
                "name",
                "version"
            ],
            "properties": {
                "allow_insecure_tls": {
                    "description": "AllowInsecureTLS allows skipping TLS certificate verification",
                    "type": "boolean"
                },
                "allowed_endpoint_types": {
                    "description": "AllowedEndpointTypes specifies which endpoint types can handle requests",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "endpoint_pools": {
                    "description": "EndpointPools defines tiered endpoint fallback pools",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.EndpointPoolDTO"
                    }
                },
                "excluded_tags": {
                    "description": "ExcludedTags are tags that a request must NOT have to match this rule",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fingerprint_ab_test": {
                    "description": "FingerprintABTest allows A/B testing different fingerprints",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.ABConfigDTO"
                        }
                    ]
                },
                "fingerprint_preset": {
                    "description": "FingerprintPreset specifies the default browser TLS fingerprint",
                    "type": "string"
                },
                "hard_timeout": {
                    "description": "HardTimeout is the maximum time allowed for a request (e.g., \"30s\")",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive indicates whether this rule is currently active",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is a human-readable name for the rule (required)",
                    "type": "string"
                },
                "pinned_cert_hash": {
                    "description": "PinnedCertHash for certificate pinning",
                    "type": "string"
                },
                "priority": {
                    "description": "Priority determines rule precedence (higher = evaluated first)",
                    "type": "integer"
                },
                "quota_key": {
                    "description": "QuotaKey is the key used for rate limit bucketing",
                    "type": "string"
                },
                "rate_limit_per_minute": {
                    "description": "RateLimitPerMinute is the maximum requests per minute",
                    "type": "integer"
                },
                "rate_limit_per_second": {
                    "description": "RateLimitPerSecond is the maximum requests per second",
                    "type": "integer"
                },
                "request_filters": {
                    "description": "RequestFilters defines bandwidth optimization filters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.RequestFilterDTO"
                        }
                    ]
                },
                "required_endpoint_caps": {
                    "description": "RequiredEndpointCaps are capability tags that endpoints must have",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "required_tags": {
                    "description": "RequiredTags are the tags that a request MUST have to match this rule",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "version": {
                    "description": "Version for optimistic locking (required for updates)",
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.UsageSummaryDTO": {
            "description": "Daily usage summary",
            "type": "object",
            "properties": {
                "breakdown": {
                    "description": "Breakdown contains per-endpoint or per-rule breakdown",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "cost_units": {
                    "description": "CostUnits is the calculated cost units",
                    "type": "number"
                },
                "date": {
                    "description": "Date in YYYY-MM-DD format",
                    "type": "string"
                },
                "total_bytes": {
                    "description": "TotalBytes is the total data transferred",
                    "type": "integer"
                },
                "total_requests": {
                    "description": "TotalRequests is the number of requests made",
                    "type": "integer"
                }
            }
        },
        "github_com_kwilabs_straw-proxy-server_internal_server_dto.UsageSummaryResponse": {
            "description": "Response containing usage summary data for a date range",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains the daily usage summaries",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kwilabs_straw-proxy-server_internal_server_dto.UsageSummaryDTO"
                    }
                },
                "end": {
                    "description": "End date in YYYY-MM-DD format",
                    "type": "string"
                },
                "start": {
                    "description": "Start date in YYYY-MM-DD format",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer token authentication (format: \"Bearer \u003ctoken\u003e\")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInforelay holds exported Swagger Info so clients can modify it
var SwaggerInforelay = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Straw Proxy Relay Server API",
	Description:      "HTTP relay proxy with fingerprinting and routing capabilities.\nThis API allows clients to proxy HTTP requests through distributed endpoints.",
	InfoInstanceName: "relay",
	SwaggerTemplate:  docTemplaterelay,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInforelay.InstanceName(), SwaggerInforelay)
}
