version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dogsled
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funcorder
    - funlen
    - godot
    - godox
    - goheader
    - goprintffuncname
    - iface
    - inamedparam
    - ineffassign
    - musttag
    - nestif
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - promlinter
    - reassign
    - staticcheck
    - tagalign
    - testableexamples
    - testpackage
    - unused
    - usestdlibvars
    - whitespace
