repos:
  - repo: local
    hooks:
      - id: make-build
        name: make build
        entry: make build
        language: system
        types: [file]
        pass_filenames: false
        always_run: true
      - id: make-test
        name: make test
        entry: make test
        language: system
        types: [file]
        pass_filenames: false
        always_run: true
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        types: [file]
        pass_filenames: false
        always_run: true
