// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: straw/v1/transport.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers         []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body            []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	TimeoutNanos    int64                  `protobuf:"varint,6,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	ReplyTo         string                 `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	MaxResponseSize int64                  `protobuf:"varint,8,opt,name=max_response_size,json=maxResponseSize,proto3" json:"max_response_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_straw_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_straw_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_straw_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *Request) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *Request) GetMaxResponseSize() int64 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Error         *ErrorInfo             `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Timing        *TimingInfo            `protobuf:"bytes,6,opt,name=timing,proto3" json:"timing,omitempty"`
	EgressId      string                 `protobuf:"bytes,7,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_straw_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_straw_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_straw_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetTiming() *TimingInfo {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *Response) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_straw_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_straw_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_straw_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ErrorInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable       bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryAfterNanos int64                  `protobuf:"varint,4,opt,name=retry_after_nanos,json=retryAfterNanos,proto3" json:"retry_after_nanos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_straw_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_straw_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_straw_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorInfo) GetRetryAfterNanos() int64 {
	if x != nil {
		return x.RetryAfterNanos
	}
	return 0
}

type TimingInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DnsLookupNanos    int64                  `protobuf:"varint,1,opt,name=dns_lookup_nanos,json=dnsLookupNanos,proto3" json:"dns_lookup_nanos,omitempty"`
	TcpConnectNanos   int64                  `protobuf:"varint,2,opt,name=tcp_connect_nanos,json=tcpConnectNanos,proto3" json:"tcp_connect_nanos,omitempty"`
	TlsHandshakeNanos int64                  `protobuf:"varint,3,opt,name=tls_handshake_nanos,json=tlsHandshakeNanos,proto3" json:"tls_handshake_nanos,omitempty"`
	FirstByteNanos    int64                  `protobuf:"varint,4,opt,name=first_byte_nanos,json=firstByteNanos,proto3" json:"first_byte_nanos,omitempty"`
	TotalNanos        int64                  `protobuf:"varint,5,opt,name=total_nanos,json=totalNanos,proto3" json:"total_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimingInfo) Reset() {
	*x = TimingInfo{}
	mi := &file_straw_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingInfo) ProtoMessage() {}

func (x *TimingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_straw_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingInfo.ProtoReflect.Descriptor instead.
func (*TimingInfo) Descriptor() ([]byte, []int) {
	return file_straw_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *TimingInfo) GetDnsLookupNanos() int64 {
	if x != nil {
		return x.DnsLookupNanos
	}
	return 0
}

func (x *TimingInfo) GetTcpConnectNanos() int64 {
	if x != nil {
		return x.TcpConnectNanos
	}
	return 0
}

func (x *TimingInfo) GetTlsHandshakeNanos() int64 {
	if x != nil {
		return x.TlsHandshakeNanos
	}
	return 0
}

func (x *TimingInfo) GetFirstByteNanos() int64 {
	if x != nil {
		return x.FirstByteNanos
	}
	return 0
}

func (x *TimingInfo) GetTotalNanos() int64 {
	if x != nil {
		return x.TotalNanos
	}
	return 0
}

var File_straw_v1_transport_proto protoreflect.FileDescriptor

const file_straw_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x18straw/v1/transport.proto\x12\bstraw.v1\"\xef\x01\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12*\n" +
	"\aheaders\x18\x04 \x03(\v2\x10.straw.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12#\n" +
	"\rtimeout_nanos\x18\x06 \x01(\x03R\ftimeoutNanos\x12\x19\n" +
	"\breply_to\x18\a \x01(\tR\areplyTo\x12*\n" +
	"\x11max_response_size\x18\b \x01(\x03R\x0fmaxResponseSize\"\x80\x02\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12*\n" +
	"\aheaders\x18\x03 \x03(\v2\x10.straw.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12)\n" +
	"\x05error\x18\x05 \x01(\v2\x13.straw.v1.ErrorInfoR\x05error\x12,\n" +
	"\x06timing\x18\x06 \x01(\v2\x14.straw.v1.TimingInfoR\x06timing\x12\x1b\n" +
	"\tegress_id\x18\a \x01(\tR\begressId\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x83\x01\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12*\n" +
	"\x11retry_after_nanos\x18\x04 \x01(\x03R\x0fretryAfterNanos\"\xdd\x01\n" +
	"\n" +
	"TimingInfo\x12(\n" +
	"\x10dns_lookup_nanos\x18\x01 \x01(\x03R\x0ednsLookupNanos\x12*\n" +
	"\x11tcp_connect_nanos\x18\x02 \x01(\x03R\x0ftcpConnectNanos\x12.\n" +
	"\x13tls_handshake_nanos\x18\x03 \x01(\x03R\x11tlsHandshakeNanos\x12(\n" +
	"\x10first_byte_nanos\x18\x04 \x01(\x03R\x0efirstByteNanos\x12\x1f\n" +
	"\vtotal_nanos\x18\x05 \x01(\x03R\n" +
	"totalNanosB<Z:github.com/beremaran/straw/internal/protocol/wirepb;wirepbb\x06proto3"

var (
	file_straw_v1_transport_proto_rawDescOnce sync.Once
	file_straw_v1_transport_proto_rawDescData []byte
)

func file_straw_v1_transport_proto_rawDescGZIP() []byte {
	file_straw_v1_transport_proto_rawDescOnce.Do(func() {
		file_straw_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_straw_v1_transport_proto_rawDesc), len(file_straw_v1_transport_proto_rawDesc)))
	})
	return file_straw_v1_transport_proto_rawDescData
}

var file_straw_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_straw_v1_transport_proto_goTypes = []any{
	(*Request)(nil),    // 0: straw.v1.Request
	(*Response)(nil),   // 1: straw.v1.Response
	(*Header)(nil),     // 2: straw.v1.Header
	(*ErrorInfo)(nil),  // 3: straw.v1.ErrorInfo
	(*TimingInfo)(nil), // 4: straw.v1.TimingInfo
}
var file_straw_v1_transport_proto_depIdxs = []int32{
	2, // 0: straw.v1.Request.headers:type_name -> straw.v1.Header
	2, // 1: straw.v1.Response.headers:type_name -> straw.v1.Header
	3, // 2: straw.v1.Response.error:type_name -> straw.v1.ErrorInfo
	4, // 3: straw.v1.Response.timing:type_name -> straw.v1.TimingInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_straw_v1_transport_proto_init() }
func file_straw_v1_transport_proto_init() {
	if File_straw_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_straw_v1_transport_proto_rawDesc), len(file_straw_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_straw_v1_transport_proto_goTypes,
		DependencyIndexes: file_straw_v1_transport_proto_depIdxs,
		MessageInfos:      file_straw_v1_transport_proto_msgTypes,
	}.Build()
	File_straw_v1_transport_proto = out.File
	file_straw_v1_transport_proto_goTypes = nil
	file_straw_v1_transport_proto_depIdxs = nil
}
